### ISSUE TITLE
LSP Errors

### ISSUE THREAD

**Issue by umop3plsdn** [rsdlt/nvim-config-files#1]
I tried following your guide up until the LSP config part and kept getting the following. I tried emailing you but the email under your contact me doesn't work. So I figured I wouldn't bother you and just copy your dotfiles from github. That has the same outcome. How did you fix this on your local copy? 

Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:289: Cannot serialise function: type not supported
stack traceback:
        [C]: in function 'encode'
        /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:289: in function 'notify'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1332: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

LSP[id=1] client has shut down while creating progress report
client shutdown during progress update

**Comment by rsdlt** [comment]
Hi, I have not received that error. In my config files I also have the LSP configured for the Lua language and Latex. Have you included only the LSP for Rust or did you keep the ones for the other languages?
