### ISSUE TITLE
E492 not an editor command on command 'Mason' or 'PackerInstall'

### ISSUE THREAD

**Issue by lidaling** [rsdlt/nvim-config-files#2]
Hi,
It is very clear with lua config. But I have troubles with commands throught blog `rust-nvim-ide-guide-walkthrough-development-debug`.
Currently I have none init.lua file  ,only lua/plug.lua file

**Comment by rsdlt** [comment]
Hi, in order to use the :PackerInstall and :Mason commands you need to have those packages installed and configured. Not sure if that is the issue that you mention?

**Comment by lidaling** [comment]
after add bellow lines ,it works. My mistake ,I don't know the basic knowledge about lua plugin.
```
lua require('plug')
lua require("mason").setup()
```
