### ISSUE TITLE
require null-ls twice?

### ISSUE THREAD

**Issue by crocme10** [rsdlt/nvim-config-files#3]
Hello,

Thanks for sharing your configuration (and the post that explains it)

I've noticed you use twice a requirement for 'null-ls'. Is there a reason for that?

* [line 109](https://github.com/rsdlt/nvim-config-files/blob/90f3391f71bb42d30e671f0c06df55200c6ef9c7/init.lua#L109)
* [line 137](https://github.com/rsdlt/nvim-config-files/blob/90f3391f71bb42d30e671f0c06df55200c6ef9c7/init.lua#L137)

Cheers,

**Comment by rsdlt** [comment]
Hi, you're welcome. Line 137 requirement is not needed. Needed to do some cleanup of my config files :)
